"""complete candidate knowledge domains

Revision ID: 8a8bf14544a8
Revises: 08e8c4b1cf4d
Create Date: 2026-07-14 21:36:30.826273
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "8a8bf14544a8"
down_revision: str | None = "08e8c4b1cf4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_candidate_id"), "audit_events", ["candidate_id"], unique=False)
    op.create_index(op.f("ix_audit_events_owner_id"), "audit_events", ["owner_id"], unique=False)
    op.create_index("ix_audit_owner_created", "audit_events", ["owner_id", "created_at"], unique=False)
    op.create_table(
        "certifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.Column("issued_date", sa.String(length=10), nullable=True),
        sa.Column("expires_date", sa.String(length=10), nullable=True),
        sa.Column("credential_id", sa.String(length=255), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_certifications_candidate_id"), "certifications", ["candidate_id"], unique=False)
    op.create_table(
        "education",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("institution", sa.String(length=255), nullable=False),
        sa.Column("degree", sa.String(length=255), nullable=True),
        sa.Column("field_of_study", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_education_candidate_id"), "education", ["candidate_id"], unique=False)
    op.create_table(
        "project_experiences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_experiences_candidate_id"), "project_experiences", ["candidate_id"], unique=False)
    with op.batch_alter_table("resumes") as batch_op:
        batch_op.add_column(sa.Column("label", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("version_number", sa.Integer(), server_default="1", nullable=False))
        batch_op.add_column(sa.Column("is_master", sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column("is_archived", sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.create_unique_constraint("uq_candidate_resume_hash", ["candidate_id", "sha256"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resumes") as batch_op:
        batch_op.drop_constraint("uq_candidate_resume_hash", type_="unique")
        batch_op.drop_column("is_archived")
        batch_op.drop_column("is_master")
        batch_op.drop_column("version_number")
        batch_op.drop_column("label")
    op.drop_index(op.f("ix_project_experiences_candidate_id"), table_name="project_experiences")
    op.drop_table("project_experiences")
    op.drop_index(op.f("ix_education_candidate_id"), table_name="education")
    op.drop_table("education")
    op.drop_index(op.f("ix_certifications_candidate_id"), table_name="certifications")
    op.drop_table("certifications")
    op.drop_index("ix_audit_owner_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_owner_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_candidate_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
